name: example

targets:
  example:
    type: tool
    platform: macOS
    deploymentTarget: "11.0"
    sources:
      - path: main.cpp
        compilerFlags:
          - -Wall
          - -Werror
          - "-std=c++20"
      - path: ../src
    settings:
      base:
        OTHER_SWIFT_FLAGS: "-warnings-as-errors"
        SWIFT_OBJC_BRIDGING_HEADER: ../include/pqrs/osx/workspace/impl/Bridging-Header.h
        SYSTEM_HEADER_SEARCH_PATHS:
          - ../include
          - vendor/include
